# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/" # Location of package manifests
    open-pull-requests-limit: 10
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
      timezone: "America/Sao_Paulo"
    assignees:
      - "dependabot"
    reviewers:
      - "paulopatto"
    commit-message:
      prefix: "build(package.json): "
      include: "scope"
    groups:
      dev-dependencies:
        patterns:
          - "@types/*"
          - "eslint*"
          - "prettier*"
          - "jest*"
          - "vitest*"
          - "typescript"
          - "tsx"
          - "@faker-js/*"
        update-types:
          - "minor"
          - "patch"
      hono-dependencies:
        patterns:
          - "@hono/*"
          - "hone"
        update-types:
          - "minor"
          - "patch"
      queue-dependencies:
        patterns:
          - "bullmq"
          - "@bull-board/*"
          - "ioredis"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:30"
      timezone: "America/Sao_Paulo"
    assignees:
      - "dependabot"
    reviewers:
      - "paulopatto"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore(ci): "
      include: "scope"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:45"
      timezone: "America/Sao_Paulo"
    assignees:
      - "dependabot"
    reviewers:
      - "paulopatto"
    open-pull-requests-limit: 3
    commit-message:
      prefix: "build(docker): "
      include: "scope"
    ignore:
      - dependency-name: "node"
        update-types: ["version-update:semver-major"]

