---
networks:
  backend:
    driver: bridge
  payment-processor:
    external: true

# Você deverá restringir o uso de: CPU e Memória em: 
# - CPU: 1,5 unidades 
# - Memória: 350MB
services:
  loadbalancer:
    image: nginx:1.25-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "20MB"
  redis:
    image: redis:alpine
    hostname: redis
    ports:
      - 6379:6379
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "100MB"
    networks:
      - backend

  api1: &api-base
      build:
        context: .
        dockerfile: Dockerfile
      environment:
        - NODE_ENV=production
        - REDIS_URL=redis://redis:6379
        - PAYMENT_PROCESSOR_RETRY_LIMIT_BEFORE_USE_FALLBACK=4
        - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-1:8001
        - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-2:8001
      ports:
        - "8081:8080"
      networks:
        - backend
        - payment-processor
      depends_on:
        - redis
      deploy:
        resources:
          limits:
            cpus: "0.45"
            memory: "115MB"

  api2:
    <<: *api-base
    ports:
        - "8082:8080"