name: Generate new release a tagging pull requests
on:
  push:
    branches:
      - main
permissions:
  contents: read
  pull-requests: write

jobs:
  update_release_draft:
    name: Generate Release version by release-drafter
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v6.1.0
        with:
          config-name: release-drafter.conf.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
