---
name: Integration test with third-party processors

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  load-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install docker-compose -y

      - name: Start services
        run: docker-compose -f vendor/docker-compose.yml up -d
      - run: docker-compose -f compose.yaml up --build -d

      - name: Wait for services to start
        run: sleep 30

      - name: Setup K6 and run load test
        uses: grafana/setup-k6-action@v1.1.0
      - uses: grafana/run-k6-action@v1.2.0
        with:
          path: tests/integration-test/rinha.js


      - name: Stop services
        run: sleep 30
      - if: always()
        run: docker-compose -f vendor/docker-compose.yml down --rmi all
      - run: docker-compose -f compose.yaml down --rmi all

